### ISSUE TITLE
New Maintainer for PalyrimOS

### ISSUE THREAD

**Issue by anupam41** [PalyrimOS/official_devices#2]
## Name and Codename of the device you want to apply for 
```
Redmi note 10 pro/max
```

## Device Tree sources

```
https://github.com/user/p_vendor_xiaomi_sweet.git
https://github.com/anupam41/p_kernel_xiaomi_sweet.git
https://github.com/anupam41/p_device_xiaomi_sweet.git
```

## What ROM's do you maintain officially/unofficially
```
Maintain syberia official a12 /pa unofficial a12
```

## How long have you been building Custom ROMs
```
2 years
```

## Any Exceptions/special concern?
```
No
```

## List of changes/patches applied to source, if any
```
No
```

### Telegram username
```
anupam41
```

### Link to your unofficial PalyrimOS Build Post other than XDA

```
Link to where you have posted your build publically.
```

**Comment by cristianvaz** [comment]
OK
